parameters:
  gender:
    1: 'Man'
    2: 'Woman'

  seek:
    1: 'Male'
    2: 'Female'

  looking_for:
    1: 'Anything'
    2: 'Serious relationship'
    3: 'Casual dating'
    4: 'Leisure and friends'
    5: 'Dinner or drink'
    6: 'Intimate'

  marital_status:
    1: 'Prefer not to say'
    2: 'Single'
    3: 'Separated'
    4: 'In a relationship'
    5: 'Married'
    6: 'Divorced'
    7: 'Widowed'
    8: 'Married'
    9: 'It''s complicated'

  eye_color:
    1: 'Black'
    2: 'Blue'
    3: 'Brown'
    4: 'Gray'
    5: 'Green'
    6: 'Hazel'
    7: 'Violet'

  hair_color:
    1: 'Black'
    2: 'Blond'
    3: 'Brown'
    4: 'Gray'
    5: 'Red'
    6: 'White'

  smoking:
    1: 'Yes'
    2: 'No'
    3: 'Casually'

  drinking:
    1: 'Yes'
    2: 'No'
    3: 'Casually'

  education:
    1: 'High school'
    2: 'Some college'
    3: 'Some University'
    4: 'Associates degree'
    5: 'Bachelors degree'
    6: 'Masters degree'
    7: 'PhD / Post Doctoral'
    8: 'Graduate degree'

  ivy_league_education:
    1: 'Yes'
    2: 'No'
    3: 'Prefer not to say'

  languages:
    10: 'Arabic'
    20: 'Chinese'
    30: 'Dutch'
    40: 'English'
    50: 'French'
    60: 'German'
    70: 'Hebrew'
    80: 'Hindi'
    90: 'Italian'
    100: 'Japanese'
    110: 'Norwegian'
    120: 'Portuguese'
    130: 'Russian'
    140: 'Spanish'
    150: 'Swedish'
    160: 'Tagalog'
    170: 'Urdu'
    1000: 'Other'

  have_children:
    1: 'Yes'
    2: 'No'

  want_children:
    1: 'Yes'
    2: 'No'
    3: 'Prefer not to say'

  open_to_person_with_kids:
    1: 'No preference'
    2: 'Yes'
    3: 'No'
    4: 'Prefer not to say'

  religion:
    10: 'Non-religious'
    20: 'New age'
    30: 'Muslim'
    40: 'Jewish'
    50: 'Catholic'
    60: 'Buddhist'
    70: 'Hindu'
    80: 'Anglican'
    90: 'Sikh'
    100: 'Methodist'
    110: 'Christian - other'
    120: 'Baptist'
    130: 'Lutheran'
    140: 'Presbyterian'
    1000: 'Other'

  ethnicity:
    10: 'Caucasian'
    20: 'Black'
    30: 'Hispanic'
    40: 'Indian'
    50: 'Middle Eastern'
    60: 'Native American'
    70: 'Asian'
    80: 'Mixed Race'
    1000: 'Other Ethnicity'

  profession:
    10: 'Accounting'
    20: 'Architecture'
    30: 'Attorney'
    40: 'Medical'
    50: 'IT industry'
    60: 'Science'
    70: 'Sales'
    80: 'Finance'
    90: 'Real estate'
    1000: 'Other'