connection_event:
    resource: "@ConnectionEventBundle/Controller/"
    type:     annotation
    prefix:   /

connection_user:
    resource: "@ConnectionUserBundle/Resources/config/routing.yml"

connection_web:
    resource: "@ConnectionWebBundle/Resources/config/routing/routing.yml"
