connection_message:
    resource: "@ConnectionMessageBundle/Controller/"
    type:     annotation
    prefix:   /

connection_web:
    resource: "@ConnectionWebBundle/Controller/"
    type:     annotation

connection_event:
    resource: "@ConnectionEventBundle/Controller/"
    type:     annotation

connection_user:
    resource: "@ConnectionUserBundle/Controller/"
    type:     annotation

connection_fos_user_bundle:
    resource: "@ConnectionUserBundle/Resources/config/fos_user_bundle.yml"

oneup_uploader:
    resource: .
    type: uploader

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message
