<?php

namespace Connection\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    public function countAll()
    {
        return $this->createQueryBuilder('e')
            ->select('COUNT(e.id) AS total')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getUpcomingEvents( Event $event, $limit = false )
    {
        $countryId  = ($event->getCountry()) ? $event->getCountry()->getId() : false;
        $stateId    = ($event->getState())   ? $event->getState()->getId()   : false;

        $qb = $this->createQueryBuilder('e')
            ->where('e.eventDate > :event_date')
            ->andWhere('e.eventDate > :current_date')
            ->setParameter('event_date', $event->getEventDate(), \Doctrine\DBAL\Types\Type::DATETIME)
            ->setParameter('current_date', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME);

        if ($stateId) {
            $qb->join('e.state', 's')
                ->andWhere('s.id = :state_id')
                ->setParameter('state_id', $stateId);
        } elseif ($countryId) {
            $qb->join('e.country', 'c')
                ->andWhere('c.id = :country_id')
                ->setParameter('country_id', $countryId);
        }

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }

    public function search( $filter = array(), $limit = false, $offset = false )
    {

        $qb = $this->createQueryBuilder('e');

        //  Search text field
        if ( !empty($filter['search']) and (strlen($filter['search']) > 3) ) {
            $qb->andWhere('e.title LIKE :search OR e.description LIKE :search')->setParameter('search', "%{$filter['search']}%");
        }

        //  Event Date From
        if ( !empty($filter['eventDateFrom'])) {
            $qb->andWhere('e.eventDate >= :event_date_from')
                ->setParameter('event_date_from', $filter['eventDateFrom'], \Doctrine\DBAL\Types\Type::DATETIME);
        }

        //  Event Date To
        if ( !empty($filter['eventDateTo'])) {
            $qb->andWhere('e.eventDate <= :event_date_to')
                ->setParameter('event_date_to', $filter['eventDateTo'], \Doctrine\DBAL\Types\Type::DATETIME);
        }


        if (!empty($filter['category'])) {
            if ($categories = $this->filterCategory($filter['category'])) {
                $qb->join('e.category', 'ec')->andWhere('ec.id IN(:categories)')->setParameter('categories', $categories);
            }
        }

        if ( $limit ) {
            $qb->setMaxResults($limit);
        }

        if ( $offset ) {
            $qb->setFirstResult($offset);
        }

        return $qb->orderBy("e.eventDate", "ASC")->getQuery()->getResult();
    }

    private function filterCategory($categories)
    {
        $result = array();
        foreach ($categories as $category) {
            $result[] = $category->getId();
        }

        return (empty($result) ? false : $result);
    }
}
