<?php

namespace Connection\UserBundle\Entity\Profile;

use Doctrine\ORM\EntityRepository;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function getGroupedByGalleryImages( $userId )
    {
        $qb = $this->createQueryBuilder('i')
                   ->select("i, g.id AS gallery_id")
                   ->join('i.gallery', 'g')
                   ->join('g.user', 'u')
                   ->where('u.id = :user_id')
                   ->setParameter('user_id', $userId);
        $images = $qb->getQuery()->getArrayResult();

        $result = array();
        foreach ($images as $image) {
            $result[$image['gallery_id']][] = $image[0];
        }

        return $result;
    }
}
