<?php

namespace Connection\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Connection\CoreBundle\Util\Location;
use Doctrine\ORM\Query;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function getLocationChildren($location, $childCategory){
        $iso = $location->getIso();
        $q = $this->createQueryBuilder('c')
            ->select('c.id, c.name')
            ->where('c.type = :type')
            ->setParameter('type', $childCategory)
            ->andWhere('c.iso LIKE :iso')
            ->setParameter('iso', $iso.'-%');
        $result = $q->getQuery()->getResult(Query::HYDRATE_ARRAY);
        return $result;
    }
}
