parameters:
    connection_user.registration.form.type.class: Connection\UserBundle\Form\Type\RegistrationType
services:
    connection_user.registration.form.type:
        class: %connection_user.registration.form.type.class%
        arguments: ['@service_container']
        tags:
          - { name: form.type, alias: connection_user_registration }
#
#    connection_user.registration.address.form.type:
#        class: %connection_user.registration.address.form.type.class%
#        arguments: ['@service_container']
#        tags:
#          - { name: form.type, alias: connection_registration_address }
