<?php

namespace Proxies\__CG__\Connection\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \Connection\UserBundle\Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'gender', 'birthdate', 'seek', 'lookingFor', 'country', 'originallyFrom', 'originallyFromCity', 'state', 'city', 'zip', 'education', 'educationIvyLeague', 'ivyLeagueUniversity', 'profession', 'income', 'religion', 'telephone', 'mobile', 'interestsAndHobbies', 'maritalStatus', 'height', 'bodyType', 'eyeColor', 'hairColor', 'smoking', 'drinking', 'haveChildren', 'wantChildren', 'livesWithChildren', 'openToPersonWithKids', 'ethnicity', 'amazonId', 'facebookId', 'googleId', 'twitterId', 'languages', 'aboutMe', 'lookingForDescription', '' . "\0" . 'Connection\\UserBundle\\Entity\\Profile' . "\0" . 'user', 'avatar', 'zodiac');
        }

        return array('__isInitialized__', 'id', 'gender', 'birthdate', 'seek', 'lookingFor', 'country', 'originallyFrom', 'originallyFromCity', 'state', 'city', 'zip', 'education', 'educationIvyLeague', 'ivyLeagueUniversity', 'profession', 'income', 'religion', 'telephone', 'mobile', 'interestsAndHobbies', 'maritalStatus', 'height', 'bodyType', 'eyeColor', 'hairColor', 'smoking', 'drinking', 'haveChildren', 'wantChildren', 'livesWithChildren', 'openToPersonWithKids', 'ethnicity', 'amazonId', 'facebookId', 'googleId', 'twitterId', 'languages', 'aboutMe', 'lookingForDescription', '' . "\0" . 'Connection\\UserBundle\\Entity\\Profile' . "\0" . 'user', 'avatar', 'zodiac');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginallyFrom($originallyFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginallyFrom', array($originallyFrom));

        return parent::setOriginallyFrom($originallyFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginallyFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginallyFrom', array());

        return parent::getOriginallyFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAboutMe($aboutMe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAboutMe', array($aboutMe));

        return parent::setAboutMe($aboutMe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAboutMe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAboutMe', array());

        return parent::getAboutMe();
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthdate($birthdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthdate', array($birthdate));

        return parent::setBirthdate($birthdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthdate', array());

        return parent::getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrinking($drinking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrinking', array($drinking));

        return parent::setDrinking($drinking);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrinking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrinking', array());

        return parent::getDrinking();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducation($education)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducation', array($education));

        return parent::setEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducationIvyLeague()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducationIvyLeague', array());

        return parent::getEducationIvyLeague();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducationIvyLeague($educationIvyLeague)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducationIvyLeague', array($educationIvyLeague));

        return parent::setEducationIvyLeague($educationIvyLeague);
    }

    /**
     * {@inheritDoc}
     */
    public function getIvyLeagueUniversity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIvyLeagueUniversity', array());

        return parent::getIvyLeagueUniversity();
    }

    /**
     * {@inheritDoc}
     */
    public function setIvyLeagueUniversity($ivyLeagueUniversity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIvyLeagueUniversity', array($ivyLeagueUniversity));

        return parent::setIvyLeagueUniversity($ivyLeagueUniversity);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', array());

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEthnicity($ethnicity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEthnicity', array($ethnicity));

        return parent::setEthnicity($ethnicity);
    }

    /**
     * {@inheritDoc}
     */
    public function getEthnicity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEthnicity', array());

        return parent::getEthnicity();
    }

    /**
     * {@inheritDoc}
     */
    public function setEyeColor($eyeColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEyeColor', array($eyeColor));

        return parent::setEyeColor($eyeColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEyeColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEyeColor', array());

        return parent::getEyeColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setHairColor($hairColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHairColor', array($hairColor));

        return parent::setHairColor($hairColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getHairColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHairColor', array());

        return parent::getHairColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setHaveChildren($haveChildren)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHaveChildren', array($haveChildren));

        return parent::setHaveChildren($haveChildren);
    }

    /**
     * {@inheritDoc}
     */
    public function getHaveChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHaveChildren', array());

        return parent::getHaveChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', array($height));

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', array());

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncome($income)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncome', array($income));

        return parent::setIncome($income);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncome', array());

        return parent::getIncome();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterestsAndHobbies($interestsAndHobbies)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterestsAndHobbies', array($interestsAndHobbies));

        return parent::setInterestsAndHobbies($interestsAndHobbies);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterestsAndHobbies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterestsAndHobbies', array());

        return parent::getInterestsAndHobbies();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguages($languages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguages', array($languages));

        return parent::setLanguages($languages);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguages', array());

        return parent::getLanguages();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivesWithChildren($livesWithChildren)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivesWithChildren', array($livesWithChildren));

        return parent::setLivesWithChildren($livesWithChildren);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivesWithChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivesWithChildren', array());

        return parent::getLivesWithChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaritalStatus($maritalStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaritalStatus', array($maritalStatus));

        return parent::setMaritalStatus($maritalStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaritalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaritalStatus', array());

        return parent::getMaritalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenToPersonWithKids($openToPersonWithKids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenToPersonWithKids', array($openToPersonWithKids));

        return parent::setOpenToPersonWithKids($openToPersonWithKids);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenToPersonWithKids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenToPersonWithKids', array());

        return parent::getOpenToPersonWithKids();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', array($profession));

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', array());

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setReligion($religion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReligion', array($religion));

        return parent::setReligion($religion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReligion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReligion', array());

        return parent::getReligion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeek($seek)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeek', array($seek));

        return parent::setSeek($seek);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeek', array());

        return parent::getSeek();
    }

    /**
     * {@inheritDoc}
     */
    public function setLookingFor($lookingFor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLookingFor', array($lookingFor));

        return parent::setLookingFor($lookingFor);
    }

    /**
     * {@inheritDoc}
     */
    public function getLookingFor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLookingFor', array());

        return parent::getLookingFor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmoking($smoking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmoking', array($smoking));

        return parent::setSmoking($smoking);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmoking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmoking', array());

        return parent::getSmoking();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setWantChildren($wantChildren)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWantChildren', array($wantChildren));

        return parent::setWantChildren($wantChildren);
    }

    /**
     * {@inheritDoc}
     */
    public function getWantChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWantChildren', array());

        return parent::getWantChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function setBodyType($bodyType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBodyType', array($bodyType));

        return parent::setBodyType($bodyType);
    }

    /**
     * {@inheritDoc}
     */
    public function getBodyType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBodyType', array());

        return parent::getBodyType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmazonId($amazonId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmazonId', array($amazonId));

        return parent::setAmazonId($amazonId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmazonId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmazonId', array());

        return parent::getAmazonId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookId($facebookId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookId', array($facebookId));

        return parent::setFacebookId($facebookId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookId', array());

        return parent::getFacebookId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleId($googleId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleId', array($googleId));

        return parent::setGoogleId($googleId);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleId', array());

        return parent::getGoogleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterId($twitterId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterId', array($twitterId));

        return parent::setTwitterId($twitterId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterId', array());

        return parent::getTwitterId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialId($fieldName, $fieldValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialId', array($fieldName, $fieldValue));

        return parent::setSocialId($fieldName, $fieldValue);
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($avatar));

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function hasAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAvatar', array());

        return parent::hasAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setZodiac($zodiac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZodiac', array($zodiac));

        return parent::setZodiac($zodiac);
    }

    /**
     * {@inheritDoc}
     */
    public function getZodiac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZodiac', array());

        return parent::getZodiac();
    }

    /**
     * {@inheritDoc}
     */
    public function setLookingForDescription($lookingForDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLookingForDescription', array($lookingForDescription));

        return parent::setLookingForDescription($lookingForDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getLookingForDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLookingForDescription', array());

        return parent::getLookingForDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginallyFromCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginallyFromCity', array($city));

        return parent::setOriginallyFromCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginallyFromCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginallyFromCity', array());

        return parent::getOriginallyFromCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', array($zip));

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', array());

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

}
