parameters:
#    connection_web.example.class: Connection\WebBundle\Example

services:
#    connection_web.example:
#        class: %connection_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
